sudo: false
addons:
  apt:
    packages:
    - libgmp-dev # https://github.com/travis-ci/travis-rubies/issues/15
language: ruby
rvm:
- '2.1.8'
- '2.2.4'
- '2.3.0'
cache: bundler
script: bundle exec rspec
notifications:
  irc:
    channels:
    - irc.freenode.net#flapjack
    template:
    - "%{message} %{repository}#%{build_number} (%{branch} - %{commit} : %{author})"
