sudo: false
language: ruby
rvm:
- '2.0'
- '2.1'
- '2.2'
cache: bundler
script: bundle exec rspec
notifications:
  irc:
    channels:
    - irc.freenode.net#flapjack
    template:
    - "%{message} %{repository}#%{build_number} (%{branch} - %{commit} : %{author})"
  slack:
    secure: B2Ievcd8gCeJdcCLnYptBJnMDU5+Pw/GPBDnBUKwOg2VG09CPt45OqNqmNhGI8/v4bZqSdYbptzLc8c/LVL4Uyc63lL5lJjvN3wLfZoqZYLmi2hwO+aThwbg7M+24oZQ2aVKDM+iWkhUWMQiAi81G0Il09RlUHh9EGOTPgXRdRE=
