sudo: false
language: ruby
rvm:
- '2.0.0-p648' # remove in March 2016, EOL
- '2.1.8'
- '2.2.4'
- '2.3.0'
cache: bundler
script: bundle exec rspec
notifications:
  irc:
    channels:
    - irc.freenode.net#flapjack
    template:
    - "%{message} %{repository}#%{build_number} (%{branch} - %{commit} : %{author})"
  slack:
    secure: OSSVSOzOOsGV58lo88tiXQiOlFt4YeRz7yQ0r2kaGV1IFpCISbLxMPTCR6qyngGJWV/QB7cgfKs39xUiAD/bU0cqz1D8BgnhLjRKcU53CymMEWV6s/TTyCgoQy+b/7DM3d7ebvEySS7fxWtApJ/DdpqbkhcgGJbNMIpaXuWd5Ro=
